---
apiVersion: v1
kind: Secret
metadata:
  name: bitwarden-mysql
  labels:
    app: bitwarden
type: Opaque
data:
  DATABASE_URL: bXlzcWwlM0EvL3Jvb3RfcnclM0FAOG14MyUyNTQwa0huJTI1MjFDWVJGMkdAdGVzdC1sZWFkZXIubXlzcWwuc3ZjLmNsdXN0ZXIubG9jYWwlM0EzMzA2L3ZhdWx0d2FyZGVu