version: '3.7'

services:
  speedtest:
    image: ilemonrain/html5-speedtest:alpine
    restart: always
    hostname: speedtest
    ports:
      - 7777:80
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M
    dns: 192.168.7.1
    networks:
      - default
networks:
  default:
    external: true
    name: dev_overlay
