version: '3'
services:
  halo:
    image: halohub/halo
    ports:
      - 8090:8090
    volumes:
      - /data/.halo:/root/.halo
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
      placement:
        constraints: [ node.labels.name == hp ]
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    dns: 192.168.7.77
networks:
  default:
    external:
      name: dev_overlay