apiVersion: elasticsearch.k8s.elastic.co/v1
kind: Elasticsearch
metadata:
  name: es
  namespace: elastic-system
spec:
  version: 7.10.2 # 这里填自己要用的版本
  nodeSets:
    - name: default
      count: 3 # 测试环境1节点就够了，生产 >= 3
      podTemplate:
        spec:
          initContainers:
            - name: install-plugins
              command:
                - sh
                - -c
                - |
                  bin/elasticsearch-plugin install --batch https://proxy.zyun.vip/https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v7.10.2/elasticsearch-analysis-ik-7.10.2.zip
              env:
                - name: READINESS_PROBE_PROTOCOL
                  value: http
      config:
        node.master: true
        node.data: true
        node.ingest: true
        node.store.allow_mmap: false
        reindex.remote.whitelist: 192.168.7.66:9200
        xpack.security.http.ssl.enabled: false
#        xpack.security.transport.ssl.enabled: false
#        xpack.security.enabled: false
      volumeClaimTemplates:
        - metadata:
            name: elasticsearch-data # 这里不要修改，进阶用法参考 ECK 官方文档
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 100Gi # 配置默认大小，allowVolumeExpansion为true后续可以扩展
            storageClassName: nfs-client # StorageClass 名称