version: "2"
services:
  ytdl_material:
    environment:
      ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
      ytdl_use_local_db: 'false'
      write_ytdl_config: 'true'
    restart: always
    depends_on:
      - ytdl-mongo-db
    volumes:
      - /data/docker/YoutubeDL-Material/appdata:/app/appdata
      - /data/docker/YoutubeDL-Material/audio:/app/audio
      - /data/docker/YoutubeDL-Material/video:/app/video
      - /data/docker/YoutubeDL-Material/subscriptions:/app/subscriptions
      - /data/docker/YoutubeDL-Material/users:/app/users
    ports:
      - "8998:17442"
    image: tzahi12345/youtubedl-material:latest
  ytdl-mongo-db:
    image: mongo
    logging:
      driver: "none"
    container_name: mongo-db
    restart: always
#    volumes:
#      - ./db/:/data/db