---
apiVersion: v1
kind: Namespace
metadata:
  name: halo2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: halo
  name: halo2
  namespace: halo2
spec:
  storageClassName: nfs-client
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: halo
  namespace: halo2
  labels:
    app: halo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: halo
  template:
    metadata:
      labels:
        app: halo
    spec:
      containers:
        - name: halo
          image: halohub/halo:2.3.0
          imagePullPolicy: Always
          volumeMounts:
            - name: data
              mountPath: /root/.halo2
          ports:
            - containerPort: 8090
          args:
#            - --spring.r2dbc.url=r2dbc:pool:mysql://10.233.53.2:3306/halodb?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#            - --spring.r2dbc.username=halo
#            # MySQL 的密码，请保证与下方 MYSQL_ROOT_PASSWORD 的变量值一致。
#            - --spring.r2dbc.password=TEM87QTPdv3QXw
#            - --spring.sql.init.platform=mysql
            # 外部访问地址，请根据实际需要修改
            - --halo.external-url=http://halo.halo2.svc.cluster.local:8090/
            # 初始化的超级管理员用户名
            - --halo.security.initializer.superadminusername=admin
            # 初始化的超级管理员密码
            - --halo.security.initializer.superadminpassword=P@88w0rd
          env:
            - name: JVM_OPTS
              value: " -Xmx2G -Xms2G "
      dnsPolicy: ClusterFirst
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: halo2
---
apiVersion: v1
kind: Service
metadata:
  name: halo
  namespace: halo2
spec:
  selector:
    app: halo
  ports:
    - name: http
      port: 8090
      targetPort: 8090
  type: ClusterIP