version: "3.7"

services:
  eureka1:
    image: registry.cn-hangzhou.aliyuncs.com/harvies/charon-eureka-server
    networks:
      - dev_overlay
    ports:
      - "8761:8761"
    environment:
      spring.cloud.inetutils.preferred-networks: 10.0.3
      charon.env: dev
      ADDITIONAL_EUREKA_SERVER_LIST: http://eureka2:8761/eureka/,http://eureka3:8761/eureka/
      EUREKA_HOST: eureka1
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: sw.dev.kikera.top:11800
      SW_AGENT_NAME: eureka1
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
      restart_policy:
        condition: any
  eureka2:
    image: registry.cn-hangzhou.aliyuncs.com/harvies/charon-eureka-server
    networks:
      - dev_overlay
    ports:
      - "8762:8761"
    environment:
      spring.cloud.inetutils.preferred-networks: 10.0.3
      charon.env: dev
      ADDITIONAL_EUREKA_SERVER_LIST: http://eureka1:8761/eureka/,http://eureka3:8761/eureka/
      EUREKA_HOST: eureka2
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: sw.dev.kikera.top:11800
      SW_AGENT_NAME: eureka2
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
      restart_policy:
        condition: any
  eureka3:
    image: registry.cn-hangzhou.aliyuncs.com/harvies/charon-eureka-server
    networks:
      - dev_overlay
    ports:
      - "8763:8761"
    environment:
      spring.cloud.inetutils.preferred-networks: 10.0.3
      charon.env: dev
      ADDITIONAL_EUREKA_SERVER_LIST: http://eureka1:8761/eureka/,http://eureka2:8761/eureka/
      EUREKA_HOST: eureka3
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: sw.dev.kikera.top:11800
      SW_AGENT_NAME: eureka3
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '2'
      restart_policy:
        condition: any
networks:
  dev_overlay:
    external: true
