version: '3'

services:
  wordpress:
    image: wordpress:latest
    volumes:
      - /data/wordpress:/var/www/html
    ports:
      - 86:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql.dev.kikera.org:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD:
    deploy:
      placement:
        constraints:
          - node.labels.name == hp
      replicas: 1
      resources:
        limits:
          memory: 200M
        reservations:
          cpus: '0.25'
          memory: 200M
    networks:
      - default
    dns: 192.168.7.77
networks:
  default:
    external:
      name: dev_overlay