version: '3'

services:
  wordpress:
    image: wordpress:latest
    volumes:
      - /data/wordpress:/var/www/html
    ports:
      - 86:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: mysql.dev.kikera.org:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: QcTVus8wXX9Caz2
    deploy:
      placement:
        constraints: [ node.labels.hostname == ArchLinux1 ]
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          cpus: '1'
          memory: 512M
    networks:
      - default
    dns: 192.168.7.3
networks:
  default:
    external:
      name: dev_overlay