# Use root/example as user/password credentials
version: '3.7'

services:
  apollo-configservice:
    image: apolloconfig/apollo-configservice:latest
    restart: always
    hostname: apollo-configservice
    ports:
      - 8080:8080
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
          cpus: '2'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql.dev.kikera.org:3306/ApolloConfigDB?characterEncoding=utf8'
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      spring.cloud.inetutils.preferred-networks: 10.0.3

  apollo-adminservice:
    image: apolloconfig/apollo-adminservice:latest
    restart: always
    hostname: apollo-adminservice
    ports:
      - 8090:8090
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
          cpus: '2'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql.dev.kikera.org:3306/ApolloConfigDB?characterEncoding=utf8'
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      spring.cloud.inetutils.preferred-networks: 10.0.3
  apollo-portal:
    image: apolloconfig/apollo-portal:latest
    restart: always
    hostname: apollo-portal
    ports:
      - 8070:8070
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
          cpus: '2'
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:mysql://mysql.dev.kikera.org:3306/ApolloPortalDB?characterEncoding=utf8'
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
      spring.cloud.inetutils.preferred-networks: 10.0.3
networks:
  default:
    external:
      name: dev_overlay
