# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.7'
services:
  oap:
    image: apache/skywalking-oap-server:8.3.0-es7
    restart: always
    ports:
      - 11800:11800
      - 12800:12800
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 400M
          cpus: '1'
    environment:
      SW_STORAGE: elasticsearch7
      SW_STORAGE_ES_CLUSTER_NODES: es.dev.kikera.org:9200
      SW_HEALTH_CHECKER: default
      SW_TELEMETRY: prometheus
    healthcheck:
      test: ["CMD-SHELL", "/skywalking/bin/swctl ch"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    dns: 192.168.7.77
  ui:
    image: apache/skywalking-ui:8.3.0
    restart: always
    ports:
      - 8084:8080
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 300M
          cpus: '1'
    environment:
      SW_OAP_ADDRESS: sw.dev.kikera.org:12800
    dns: 192.168.7.77
