apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: blog
  labels:
    app: wordpress
spec:
  selector:
    matchLabels:
      app: wordpress
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: wordpress
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: wdport
          env:
            - name: WORDPRESS_DB_HOST
              value: test-leader.mysql.svc.cluster.local:3306
            - name: WORDPRESS_DB_USER
              value: wordpress
            - name: WORDPRESS_DB_PASSWORD
              value: QcTVus8wXX9Caz2
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: blog
spec:
  selector:
    app: wordpress
  # type: NodePort
  type: LoadBalancer
  ports:
    - name: wordpressport
      protocol: TCP
      port: 80
#      nodePort: 32255
#      targetPort: wdport

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
  namespace: blog
spec:
  ingressClassName: nginx
  rules:
    - host: blog.kikera.org
      http:
        paths:
          - pathType: Prefix
            backend:
              service:
                name: wordpress
                port:
                  number: 80
            path: /
  # This section is only required if TLS is to be enabled for the Ingress
  #tls:
  #  - hosts:
  #    - blog.kikera.org
  #    secretName: example-tls
