version: "3.7"

services:
  eureka1:
    image: registry.cn-hangzhou.aliyuncs.com/harvies/charon-socks-proxy-server
    networks:
      - default
    restart: always
    ports:
      - "1088:1088"
    environment:
      SW_AGENT_COLLECTOR_BACKEND_SERVICES: sw.dev.kikera.top:11800
      SW_AGENT_NAME: charon-socks-proxy-server
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 300M
          cpus: '4'
networks:
  default:
    external:
      name: dev_overlay
