version: "3"
services:
  chinesesubfinder:
    image: allanpk716/chinesesubfinder:latest
    volumes:
      - /volume2/docker/chinesesubfinder/config:/config
      - /volume2/docker/chinesesubfinder/cache:/app/cache
      - /volume3/video/:/media
    environment:
      - PUID=1026
      - PGID=100
      - TZ=Asia/Shanghai
    ports:
      - 19035:19035
    restart: unless-stopped