DROP TABLE IF EXISTS user;

CREATE TABLE user
(
	id BIGINT(20) NOT NULL COMMENT '主键ID',
	name VARCHAR(30) NULL DEFAULT NULL COMMENT '姓名',
	age INT(11) NULL DEFAULT NULL COMMENT '年龄',
	email VARCHAR(50) NULL DEFAULT NULL COMMENT '邮箱',
	biz_id BIGINT(20) NULL DEFAULT NULL COMMENT 'bizId',
    deleted BIGINT(20) NOT NULL DEFAULT NULL COMMENT 'deleted',
	PRIMARY KEY (id)
);