# Use root/example as user/password credentials
version: '3.7'

services:
  mysql:
    image: mysql:8.0
    volumes:
      - /data/mysql:/var/lib/mysql
    restart: always
#    command: --skip-grant-tables  ## 跳过密码验证启动，找回密码时使用
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD:
    networks:
      - default
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 500M
        reservations:
          memory: 500M
      placement:
        constraints:
          - node.labels.name == hp
networks:
  default:
    external:
      name: dev_overlay
