# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
   push:
     branches: [ master ]
   pull_request:
     # The branches below must be a subset of the branches above
     branches: [ master ]
   release:
    types: [ created ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B install -Pgithub -s $GITHUB_WORKSPACE/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/.m2/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

#    - name: Notify
#      run: curl 'https://api.kikera.top:4433/notify/send?title=charon-GitHub%20Actions&text=%E9%80%9A%E7%9F%A5-charon%20build%20success!' &
