version: '3.7'

services:
  dubbo-admin:
    image: harvies/dubbo-admin:latest
    restart: always
    hostname: dubbo-admin
    ports:
      - 2179:8080
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 300M
        reservations:
          memory: 300M
    environment:
      - admin.registry.address=zookeeper://zk.dev.kikera.org:2181
      - admin.config-center=zookeeper://zk.dev.kikera.org:2181
      - admin.metadata-report.address=zookeeper://zk.dev.kikera.org:2181
      - admin.check.authority=false
      - admin.root.user.name=admin
      - admin.root.user.password=
    dns: 192.168.7.77
    networks:
      - default
networks:
  default:
    external: true
    name: dev_overlay
